apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password




  
      # containers:
      # - name: jenkins
      #   image: vfarcic/jenkins
      #   env:
      #   - name: JENKINS_OPTS
      #     value: --prefix=/jenkins
      #   - name: SECRETS_DIR
      #     value: /etc/secrets
      #   volumeMounts:
      #   - name: jenkins-home
      #     mountPath: /var/jenkins_home
      #   - name: jenkins-creds
      #     mountPath: /etc/secrets
      # volumes:
      # - name: jenkins-home
      #   emptyDir: {}
      # - name: jenkins-creds
      #   secret:
      #     secretName: my-creds
      #     defaultMode: 0444
      #     items:
      #     - key: username
      #       path: jenkins-user
      #     - key: password
      #       path: jenkins-pass

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017




